### ISSUE TITLE
Stream commands are broken after upgrading to v9.2.0

### ISSUE THREAD

**Issue by minghsu0107** [redis/go-redis#2731] opened 2023-09-23 17:22 UTC
Encountered following errors after upgrading from v9.1 to v9.2.0:

```
type redis.UniversalClient has no field or method XAdd
type redis.UniversalClient has no field or method XGroupCreateMkStream
type redis.UniversalClient has no field or method XReadGroup
type redis.UniversalClient has no field or method XRead
type redis.UniversalClient has no field or method XPendingExt
type redis.UniversalClient has no field or method XClaim
type redis.UniversalClient has no field or method XInfoConsumers
type redis.UniversalClient has no field or method XGroupDelConsumer
type redis.Pipeliner has no field or method XAck
```

**Comment by sethrylan** [comment] 2023-09-27 15:36
Duplicate of https://github.com/redis/go-redis/issues/2723

Resolved with https://github.com/redis/go-redis/pull/2725 and released in v9.2.1

**Closed** 2023-10-04 12:08 UTC
